import { MD3LightTheme, MD3DarkTheme, configureFonts } from 'react-native-paper';

// Colores personalizados basados en tu esquema actual
const customColors = {
  primary: '#2E7D9B',
  primaryContainer: '#A1CEDC',
  secondary: '#5A9FBC',
  secondaryContainer: '#D4E8F0',
  tertiary: '#7B5EA7',
  tertiaryContainer: '#EDD8FF',
  surface: '#FAFAFA',
  surfaceVariant: '#E7E7E7',
  surfaceDisabled: '#F5F5F5',
  background: '#FFFFFF',
  error: '#BA1A1A',
  errorContainer: '#FFDAD6',
  onPrimary: '#FFFFFF',
  onPrimaryContainer: '#001F2A',
  onSecondary: '#FFFFFF',
  onSecondaryContainer: '#1A3E4E',
  onTertiary: '#FFFFFF',
  onTertiaryContainer: '#2B0052',
  onSurface: '#1C1B1F',
  onSurfaceVariant: '#49454F',
  onSurfaceDisabled: '#949494',
  onError: '#FFFFFF',
  onErrorContainer: '#410002',
  onBackground: '#1C1B1F',
  outline: '#79747E',
  outlineVariant: '#CAC4D0',
  inverseSurface: '#313033',
  inverseOnSurface: '#F4EFF4',
  inversePrimary: '#9FCADB',
  shadow: '#000000',
  scrim: '#000000',
  backdrop: 'rgba(0, 0, 0, 0.4)',
  elevation: {
    level0: 'transparent',
    level1: '#F5F5F5',
    level2: '#EFEFEF',
    level3: '#E8E8E8',
    level4: '#E0E0E0',
    level5: '#D8D8D8',
  },
};

const fontConfig = {
  fontFamily: 'System',
};

export const MD3LightThemeCustom = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    ...customColors,
  },
  fonts: configureFonts({ config: fontConfig }),
};

export const MD3DarkThemeCustom = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#9FCADB',
    primaryContainer: '#1E5F7B',
    secondary: '#B8D4E0',
    secondaryContainer: '#3A6B82',
    tertiary: '#D4B8FF',
    tertiaryContainer: '#5C3E8C',
    surface: '#1C1B1F',
    surfaceVariant: '#49454F',
    surfaceDisabled: '#2A2A2A',
    background: '#121212',
    error: '#FFB4AB',
    errorContainer: '#93000A',
    onPrimary: '#003547',
    onPrimaryContainer: '#C4E7F7',
    onSecondary: '#203740',
    onSecondaryContainer: '#D4E8F0',
    onTertiary: '#3E1E6C',
    onTertiaryContainer: '#EDD8FF',
    onSurface: '#E6E1E5',
    onSurfaceVariant: '#CAC4D0',
    onSurfaceDisabled: '#8C8C8C',
    onError: '#690005',
    onErrorContainer: '#FFDAD6',
    onBackground: '#E6E1E5',
    outline: '#938F99',
    outlineVariant: '#49454F',
    inverseSurface: '#E6E1E5',
    inverseOnSurface: '#313033',
    inversePrimary: '#2E7D9B',
    shadow: '#000000',
    scrim: '#000000',
    backdrop: 'rgba(0, 0, 0, 0.6)',
    elevation: {
      level0: 'transparent',
      level1: '#252529',
      level2: '#2A2A2E',
      level3: '#303034',
      level4: '#363639',
      level5: '#3C3C3F',
    },
  },
  fonts: configureFonts({ config: fontConfig }),
};
